### PR TITLE
change the way EventParticipation status are merged

### LINKED ISSUE #25: [InvalidArgumentException] Status not recognized ; Had "2", expected one of "-1", "0", "1"
```
Exception trace:
 () at calendart/calendart/src/EventParticipation.php:144
 CalendArt\EventParticipation->setStatus() at calendart/office365-adapter/src/Model/Event.php:330
 CalendArt\Adapter\Office365\Model\Event::hydrate() at calendart/office365-adapter/src/Api/EventApi.php:61
 CalendArt\Adapter\Office365\Api\EventApi->requestEvents() at calendart/office365-adapter/src/Api/EventApi.php:142
 CalendArt\Adapter\Office365\Api\EventApi->getCalendarView() at ...
```

### PR DESCRIPTION
**Pull request by lunika**
Fix #25

### CODE REVIEW

**Comment by lunika** [comment]
ping @Taluu

File: src/Model/EventParticipation.php [hunk 1]
```diff
@@ -50,7 +50,7 @@ public function setType($type)
     /** {@inheritDoc} */
     public static function getAvailableStatuses()
     {
-        return parent::getAvailableStatuses() + [static::STATUS_NONE, static::STATUS_ORGANIZER];
+        return array_merge(parent::getAvailableStatuses(), [static::STATUS_NONE, static::STATUS_ORGANIZER]);
```
Comment (Taluu) [inline src/Model/EventParticipation.php:53]: strange, as `+` between two arrays is supposed to merge two arrays, but php I guess. :trollface:

**Comment by Taluu** [comment]
You actually don't have to include phpunit requirements (it should be on the dev responsability to install it, globally (phar or whatever)). Please remove the commits that does that. :}

cf https://github.com/Calendart/Office365Adapter/commit/a923ac1561be77b075576762dc6af72512cb292c

File: src/Model/EventParticipation.php (hunk 1 above)
Comment (lunika) [inline src/Model/EventParticipation.php:53]: It works only for associative array in my case. BTW `array_merge` is explicit and I understand at the first what you want to do

**Comment by lunika** [comment]
done

**Comment by lunika** [comment]
I removed phpunit

File: test/Model/EventParticipationTest.php [hunk 2]
```diff
@@ -16,8 +14,8 @@ class EventParticipationTest extends \PHPUnit_Framework_TestCase
      */
     public function testSetStatus($status)
     {
-        $event = $this->prophesize(AbstractEvent::class);
-        $user = $this->prophesize(User::class);
+        $event = $this->prophesize("CalendArt\\AbstractEvent");
+        $user = $this->prophesize("CalendArt\\User");
```
Comment (Taluu) [inline test/Model/EventParticipationTest.php:18]: I wouldn't mind upping the requirements to php 5.6 though :trollface: (but it would need a minor release)

**Comment by Taluu** [comment]
Awesome. Merging.
